export const cartActionTypes = {
  TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
  ADD_ITEM: "ADD_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",
  REMOVE_QUANTITY: "REMOVE_QUANTITY",
  CLEAR_CART: "CLEAR_CART",
};
